#!/usr/bin/env bash
# Publish the RKE2 cluster, which now lives in libvirt guests, on the host's
# public address. Run on the HOST (the hypervisor), not inside a VM.
#
# ADR-015 moved the cluster into three VMs on one machine. The machine has one
# routable IPv4 and the guests have none, so the host has to forward :80 and
# :443 into the cluster. That takes THREE rules across TWO tables, and each
# missing one fails in a different, misleading way:
#
#   nat/PREROUTING DNAT     rewrite the destination to a cluster node. Must be
#                           INSERTED at the top: Calico's cali-PREROUTING and
#                           RKE2's CNI-HOSTPORT-DNAT live in the same chain, and
#                           an APPENDED rule is never reached -- during a
#                           cutover that means traffic silently keeps going to
#                           whatever was serving before.
#                           It MUST be scoped with -d <public ip>. Unscoped, it
#                           also matches traffic LEAVING the guests, because
#                           forwarded packets traverse PREROUTING too: every
#                           outbound HTTPS call from the cluster gets bent back
#                           into our own ingress. The symptom is a TLS error
#                           naming Traefik's default certificate for a public
#                           host, and it breaks ACME and registry pulls.
#
#   filter/LIBVIRT_FWI      libvirt's default network is outbound-only. It
#                           accepts RELATED,ESTABLISHED and ends the chain with
#                           REJECT --reject-with icmp-port-unreachable, so a NEW
#                           inbound connection is refused after the host has
#                           already accepted it. Reads as "the service is down";
#                           the tell is an instant failure rather than a hang.
#
#   nat/POSTROUTING MASQ    NAT loopback. Without it a guest that resolves the
#                           public hostname is DNAT-ed to a neighbour on the
#                           same bridge, which replies directly and bypasses
#                           conntrack. cert-manager's HTTP-01 self-check runs
#                           over exactly this path, so renewals fail while the
#                           site looks perfectly healthy from outside.
#
# Idempotent. Re-run it after anything that rewrites iptables: rke2-killall.sh,
# a libvirt network restart, a reboot. Installs a systemd unit and a libvirt
# network hook so those cases are handled without anyone remembering to.
#
# NOT iptables-persistent: netfilter-persistent save would snapshot Calico's and
# RKE2's entire rule set and replay it at boot before either is running.
set -euo pipefail

TARGET="${TARGET:-192.168.122.11}"          # cluster node that receives the traffic
SUBNET="${SUBNET:-192.168.122.0/24}"        # the libvirt network
PORTS="${PORTS:-80,443}"

cat > /usr/local/sbin/vaullet-ingress-rules.sh <<'SCRIPT'
#!/usr/bin/env bash
# Generated by gitops/bootstrap/04-ingress.sh -- see it for why each rule exists.
set -euo pipefail

PUBLIC_IP="${PUBLIC_IP:-$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')}"
TARGET="${TARGET:-192.168.122.11}"
SUBNET="${SUBNET:-192.168.122.0/24}"
PORTS="${PORTS:-80,443}"

[ -n "$PUBLIC_IP" ] || { echo "cannot determine the public address" >&2; exit 1; }

# On boot we can beat libvirt to creating its chains.
for _ in $(seq 1 30); do
    iptables -t filter -S LIBVIRT_FWI >/dev/null 2>&1 && break
    sleep 2
done

ins() { # ins <table> <chain> <rule...> -- at the top, only if not already there
    local table=$1 chain=$2
    shift 2
    iptables -t "$table" -C "$chain" "$@" 2>/dev/null \
        || iptables -t "$table" -I "$chain" 1 "$@"
}

ins nat    PREROUTING   -d "${PUBLIC_IP}/32" -p tcp --dport 443 -j DNAT --to-destination "${TARGET}:443"
ins nat    PREROUTING   -d "${PUBLIC_IP}/32" -p tcp --dport 80  -j DNAT --to-destination "${TARGET}:80"
ins filter LIBVIRT_FWI  -d "${TARGET}/32" -o virbr0 -p tcp -m multiport --dports "$PORTS" -j ACCEPT
ins nat    POSTROUTING  -s "$SUBNET" -d "${TARGET}/32" -p tcp -m multiport --dports "$PORTS" -j MASQUERADE

echo "ingress rules in place: ${PUBLIC_IP} -> ${TARGET}"
SCRIPT
chmod 0755 /usr/local/sbin/vaullet-ingress-rules.sh

cat > /etc/systemd/system/vaullet-ingress.service <<UNIT
[Unit]
Description=Publish the RKE2 VM cluster on the host public IP
After=network-online.target libvirtd.service virtnetworkd.service
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
Environment=TARGET=${TARGET}
Environment=SUBNET=${SUBNET}
Environment=PORTS=${PORTS}
ExecStart=/usr/local/sbin/vaullet-ingress-rules.sh

[Install]
WantedBy=multi-user.target
UNIT

# libvirt rebuilds LIBVIRT_FWI from scratch every time the network starts, which
# drops our ACCEPT. The hook puts it back without waiting for a reboot.
mkdir -p /etc/libvirt/hooks
cat > /etc/libvirt/hooks/network <<'HOOK'
#!/bin/sh
# $1 network  $2 operation
[ "$1" = "default" ] && [ "$2" = "started" ] \
    && /usr/local/sbin/vaullet-ingress-rules.sh >/dev/null 2>&1
exit 0
HOOK
chmod 0755 /etc/libvirt/hooks/network

systemctl daemon-reload
systemctl enable --now vaullet-ingress.service

echo
echo "nat/PREROUTING:"
iptables -t nat -S PREROUTING | grep DNAT | sed 's/^/  /'
echo "filter/LIBVIRT_FWI:"
iptables -S LIBVIRT_FWI | grep ACCEPT | sed 's/^/  /'
echo "nat/POSTROUTING:"
iptables -t nat -S POSTROUTING | grep MASQUERADE | sed 's/^/  /'
echo
echo "Verify FROM ANOTHER MACHINE -- traffic this host originates to its own"
echo "address goes through OUTPUT, never PREROUTING, so a local curl proves nothing:"
echo "  curl -I https://vaullet.dev/"
